language: c
dist: trusty

# temporary workaround for https://github.com/travis-ci/travis-ci/issues/8892
sudo: required
group: deprecated-2017Q4

compiler:
  - gcc

os:
  - linux

before_install:
  - "CONFIG_FLAG="
  - "JOBS=-j`nproc`"

before_script:
  - "echo JOBS=$JOBS"
  - "uname -a"
  - "uname -r"
  - "rm -fr .ext autom4te.cache"
  - "echo $TERM"
  - "> config.status"
  - "sed -f tool/prereq.status Makefile.in common.mk > Makefile"
  - "make update-config_files"
  - "make touch-unicode-files"
  - "make -s $JOBS srcs UNICODE_FILES=."
  - "requests=; for req in ${RUBYSPEC_PULL_REQUEST//,/ }; do
      requests=\"$requests +refs/pull/$req/merge:\";
    done"
  - "${requests:+git -C spec/ruby -c user.email=none -c user.name=none pull --no-edit origin $requests}"
  - "${requests:+git -C spec/ruby log --oneline origin/master..@}"
  - "rm config.status Makefile rbconfig.rb .rbconfig.time"
  - "mkdir build config_1st config_2nd"
  - "chmod -R a-w ."
  - "chmod u+w build config_1st config_2nd"
  - "cd build"
  - "../configure -C --disable-install-doc --with-gcc=$CC $CONFIG_FLAG"
  - "cp -pr config.cache config.status .ext/include ../config_1st"
  - "make reconfig"
  - "cp -pr config.cache config.status .ext/include ../config_2nd"
  - "(cd .. && exec diff -ru config_1st config_2nd)"
  - "make -s $JOBS"

script:
  - "make -s test TESTOPTS=--color=never"
  - "make -s $JOBS test-all -o exts TESTOPTS='-q --color=never --job-status=normal'"
  - "make -s $JOBS test-spec MSPECOPT=-j"

# Branch matrix.  Not all branches are Travis-ready so we limit branches here.
branches:
  only:
    - trunk
    - ruby_2_2
    - ruby_2_3
    - ruby_2_4
    - ruby_2_5
    - /^feature\//
    - /^bug\//
